DROP TABLE IF EXISTS passwords;

CREATE TABLE passwords (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_URL TEXT NOT NULL,
    email TEXT NOT NULL,
    email_password TEXT NOT NULL
);